# Generated by Django 5.0.2 on 2024-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=240)),
                ('spanish', models.CharField(max_length=240)),
                ('info', models.TextField()),
            ],
        ),
    ]
