# Generated by Django 5.0.2 on 2024-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='box',
            field=models.IntegerField(default=0),
        ),
    ]
